In [2]:
# open this jupyter notebook with Datalore
import torch 
import numpy as np

### tensor初始化
pytorch的数据以tensor的方式储存。可以通过list和tuple等python内部数据结构直接生成tensor，也可以从numpy ndarray来生成。

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

np_array=np.array(data)
x_np = torch.tensor(np_array)

In [4]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor:\n {x_rand}\n")

ones tensor:
 tensor([[1, 1],
        [1, 1]])

random tensor:
 tensor([[0.7063, 0.3028],
        [0.0978, 0.9043]])



shape是tuple类型，描述维数，可以指定维数生成tensor

In [5]:
shape=tuple([2,3])
rand_tensor = torch.rand(shape)
ones_tensor= torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"random tensor:\n {rand_tensor}\n")
print(f"ones tensor:\n {ones_tensor}\n")
print(f"zeros tensor: \n {zeros_tensor}\n")

random tensor:
 tensor([[0.3897, 0.0968, 0.6807],
        [0.7664, 0.2755, 0.2556]])

ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



### tensor的属性

In [6]:
tensor=torch.rand((3,4))
print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device: tensor is strored on: {tensor.device}")

shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device of tensor: cpu


## tensor运算
所有的tensor运算都可以在GPU上运行

In [8]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

cpu


In [15]:
tensor = torch.ones((4,4))
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
tensor[:,1]=0 
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [19]:
t2 = torch.cat([tensor,tensor,tensor], dim=0)
t2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
# element-wise multiply
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)}")
print(f"tensor*tensor: \n {tensor * tensor}")

tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor*tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
