In [1]:
import torch 
import numpy as np

### tensor初始化
pytorch的数据以tensor的方式储存。可以通过list和tuple等python内部数据结构直接生成tensor，也可以从numpy ndarray来生成。

In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

np_array=np.array(data)
x_np = torch.tensor(np_array)

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor:\n {x_rand}\n")

ones tensor:
 tensor([[1, 1],
        [1, 1]])

random tensor:
 tensor([[0.2346, 0.5932],
        [0.0767, 0.9868]])



shape是tuple类型，描述维数，可以指定维数生成tensor

In [9]:
shape=tuple([2,3])
rand_tensor = torch.rand(shape)
ones_tensor= torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"random tensor:\n {rand_tensor}\n")
print(f"ones tensor:\n {ones_tensor}\n")
print(f"zeros tensor: \n {zeros_tensor}\n")

random tensor:
 tensor([[0.4169, 0.4734, 0.7635],
        [0.0917, 0.9181, 0.9614]])

ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



### tensor的属性

In [10]:
tensor=torch.rand((3,4))
print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print()